In [21]:
import numpy as np
import tensorflow as tf

In [71]:
np.array([[[1,2], [3,4]], [[5,6], [7,8]]])[:611]

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [57]:
np.array([[[1,2], [3,4]], [[5,6], [7,8]]])[:,:,0] * [[1],[2]]

array([[ 1,  3],
       [10, 14]])

In [90]:
x = tf.constant([[[1,2,3,4,5,6,7,8,9], [1,2,3,4,5,6,7,8,9]]])
t = tf.where(tf.greater(x, 5))
g = tf.gather_nd(x, [[0,0]])
sess = tf.Session()
with sess.as_default():
    print(g.eval())

[[1 2 3 4 5 6 7 8 9]]


In [75]:
t

False

In [33]:
tf.multiply

TensorShape([Dimension(2), Dimension(1), Dimension(2)])